### ISSUE TITLE
Upcoming Google Maps deprecation in Places Library

### ISSUE THREAD

**Issue by jrrdnx** [nthmedia/entry-gps-coordinates#10]
I'm not sure if this currently affects this plugin, but wanted to make you aware if so. We received this email regarding the Places Library, Maps Javascript API:

> Currently, the Places Library, Maps JavaScript API exposes in its PlaceResult object the properties:

> -  utc_offset, which is returned on Place Details requests and
> -  opening_hours.open_now, which is returned on Place Details, Find Place, Nearby Search and Text Search requests.

> On November 20, 2019, we deprecated these properties to bring consistency across Places API clients on different platforms (the Maps JavaScript API, the Places SDK for Android, the Places SDK for iOS).

> These properties have been replaced as follows:

> - utc_offset, by utc_offset_minutes
> - opening_hours.open_now, by the isOpen() method in Place Details requests only.

> Additionally, for Find Place, Nearby Search and Text Search requests, we provide alternative solutions for determining whether a place is open.

> As a result, starting November 20, 2020, the Places Library, Maps JavaScript API will stop accepting utc_offset and the nested field opening_hours.open_now in the fields parameter and stop returning them in response to such requests. Instead, you will receive the ‘Unsupported field name’ error when using these properties in the fields parameter and the value ‘undefined’ when reading these properties from the PlaceResult object in the response.

> If you are not already doing so, using the fields parameter in Place Details requests will save you money in case you don’t need all the fields for returned places. If you do not specify at least one field with a request, or if you omit the fields parameter from a request, all possible fields will be returned, and you will be billed accordingly, for all data SKUs.

**Comment by niektenhoopen** [comment]
Hi Jarrod! Thank you for forwarding the message. There is no usage of `utc_offset` and `opening_hours` in the plugin so I think we should be fine. If you think otherwise, please let me know, in that case there is still plenty of time to come up with a fix :)
