### ISSUE TITLE
This page can't load Google Maps correctly message when searching for an address

### ISSUE THREAD

**Issue by colin-oos** [nthmedia/entry-gps-coordinates#11]
I get the following message in craft when I attempt to enter an address:

<img width="665" alt="image" src="https://user-images.githubusercontent.com/46458035/96780759-de56b000-13ba-11eb-8fb1-27955066d22b.png">

Could this be related to changes made to Google's API?

**Comment by niektenhoopen** [comment]
Does the console say something? I think it should give a reason why it's not loading correctly.
