### ISSUE TITLE
array_key_exists(): Argument #2 ($array) must be of type array

### ISSUE THREAD

**Issue by thunder87** [nthmedia/entry-gps-coordinates#14]
Getting error on line 131 (src/fields/EntryCoordinates.php)..

Works perfectly on dev, but as soon as i publish to prod it fails.

```
return new EntryCoordinatesModel([
    'coordinates' => array_key_exists('coordinates', $value) ? $value['coordinates'] : null, <-- Error
    'searchQuery' => array_key_exists('searchQuery', $value) ? $value['searchQuery'] : null,
]);
```

Latest craft and php v8 (prod) - v7.4 (dev)

My guess is that it could be a php v8 compatibility issue with the array_key_exists?

**Comment by niektenhoopen** [comment]
My first guess would be that PHP 8 is stricter with the type of $value.

What error do you get?

**Comment by thunder87** [comment]
Happens when you click ‘create new entry’ and it errors out before even seeing the form.

**Comment by niektenhoopen** [comment]
> Happens when you click ‘create new entry’ and it errors out before even seeing the form.
I can not reproduce it when creating a new entry but I can reproduce it when saving an entry. I have created a fix but since I cannot reproduce it completely, I hope that you would be able to test it.

**Comment by niektenhoopen** [comment]
@thunder87 I just released v1.3.1. Can you please test it?

**Comment by thunder87** [comment]
Seems to have fixed the issue, thank you for the quick response! :)

**Comment by niektenhoopen** [comment]
Vær så god!
