### ISSUE TITLE
Google Maps JavaScript API error: InvalidKeyMapError

### ISSUE THREAD

**Issue by a-rbsn** [nthmedia/entry-gps-coordinates#19]
Hi nthmedia,

Recently we've been getting this error in pages that use the plugin:
```
Google Maps JavaScript API error: InvalidKeyMapError
https://developers.google.com/maps/documentation/javascript/error-messages#invalid-key-map-error
```

Is there a way we can put our own Google Maps API key in for the plugin to begin working again? Currently we can't select locations.

Best,
Andy

**Comment by niektenhoopen** [comment]
Hi @a-rbsn, did you enter your key in the field settings of the Coordinates field?

**Comment by a-rbsn** [comment]
Ah I knew it must have been somewhere! Thank you, for some reason I was looking for plugin settings, I'll update the key and see if I can get it working, thanks for your super-prompt reply.

**Comment by niektenhoopen** [comment]
@a-rbsn Yeah, I agree that would probably be a better place with the knowledge of today 😉
