### ISSUE TITLE
Feature Request: Get zoom and remember zoom

### ISSUE THREAD

**Issue by RyanRoberts** [nthmedia/entry-gps-coordinates#21]
First of all thanks for the free plugin! It's very useful.

If you have the time there are a couple of things that would make the dev and author experience a little better.

1. A way to get the zoom level set in the field and use that in templates
2. Remember the zoom level set within the field when an entry is saved

Wait, one more… can the default zoom level / location of the field be a world view rather than Amsterdam? 

TIA

**Comment by saschapi** [comment]
I second the wish to define a base zoom level and location for the field. World View wouldn't do it for my project. Instead it would be nice to select a location as starting point in the field config. (could even be just plain coordinates).

**Comment by niektenhoopen** [comment]
@RyanRoberts @saschapi I have added this to the latest release (2.2.0). 

- Default zoom level and center coordinates can be set in the field
- Zoom level is stored when saving an entry
- A twig helper has been added to retrieve the zoom level (see readme)

Thank you for your input!
