### ISSUE TITLE
If the field is required the entry still can be saved without warning

### ISSUE THREAD

**Issue by saschapi** [nthmedia/entry-gps-coordinates#22]
Title says ist all. If the field is set to required you still can save the entry without problems and without a warning.

**Comment by niektenhoopen** [comment]
Thanks for creating the issue@saschapi! I have just release a new version. Can you please verify that it's now fixed?

**Comment by saschapi** [comment]
> Thanks for creating the issue@saschapi! I have just release a new version. Can you please verify that it's now fixed?

Works like expected! thanks for the quick fix!
