### ISSUE TITLE
latitude and longitude filters are removing negative sign from values

### ISSUE THREAD

**Issue by jrrdnx** [nthmedia/entry-gps-coordinates#5]
The coordinates field is being saved to the database properly, and dumping both the raw field and using the `|coordinates` filter show the latitude/longitude as having the negative sign, but when using either the  `|latitude` or `|longitude` filter it outputs the absolute value instead.

**entry.mapLocation**
```
array(2) { ["coordinates"]=> string(23) "-41.6571637,-84.9918667" ["searchQuery"]=> string(0) "" }
```
**entry.mapLocation|coordinates**
```
string(23) "-41.6571637,-84.9918667"
```
**entry.mapLocation|latitude**
```
string(10) "41.6571637"
```
**entry.mapLocation|longitude**
```
string(10) "84.9918667"
```

**Comment by niektenhoopen** [comment]
Thanks! I obviously have to travel to other parts of the globe with a negative latitude and/or longitude ;)

Fixed in v1.2.1 d7167728460a3b8f35e45f71f9178448861afddf
