### ISSUE TITLE
CraftQL and GraphQL support

### ISSUE THREAD

**Issue by preston-method** [nthmedia/entry-gps-coordinates#6]
Hi

When I try to access the Map Coordinates from CraftQL or GraphQL i get an internal server error response the JSON response. See snipper result below:

 "errors": [
    {
      "message": "Internal server error",
      "category": "internal",
      "locations": [
        {
          "line": 9,
          "column": 4
        }
      ],
      "path": [
        "entries",
        0,
        "mapCoordinates"
      ]
    },

**Comment by niektenhoopen** [comment]
@preston-method I havent used GraphQL at all to be honest. I will try to look into it next week.

Is there anything to be found in the logs? What does this line 9 column 4 mean?
