### ISSUE TITLE
CP throws Parse error after adding Field to a Section

### ISSUE THREAD

**Issue by tsawitzki** [nthmedia/entry-gps-coordinates#8]
Steps to reproduce:

1. get a fresh API key from Google account registered with Maps JavaScript API and Places API
2. create new Field "Entry Coordinates" in CP and include API key
3. add Field to Section field layout
4. go to sections
5. select an entry to edit
6. CP crashes with the following error message:

`ParseError: syntax error, unexpected 'const' (T_CONST), expecting variable (T_VARIABLE) in /Users/Tobias/Development/fiftyfifty-app-cms/vendor/nthmedia/entry-gps-coordinates/src/models/EntryCoordinatesModel.php:10
Stack trace:
#0 /Users/Tobias/Development/fiftyfifty-app-cms/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile('/Users/Tobias/D...')
#1 [internal function]: Composer\Autoload\ClassLoader->loadClass('nthmedia\\entryg...')
#2 /Users/Tobias/Development/fiftyfifty-app-cms/vendor/nthmedia/entry-gps-coordinates/src/fields/EntryCoordinates.php(130): spl_autoload_call('nthmedia\\entryg...')
#3 /Users/Tobias/Development/fiftyfifty-app-cms/vendor/craftcms/cms/src/base/Element.php(2680): nthmedia\entrygpscoordinates\fields\EntryCoordinates->normalizeValue(Array, Object(craft\elements\Entry))
#4 /Users/Tobias/Development/fiftyfifty-app-cms/vendor/craftcms/cms/src/base/Element.php(1104): craft\base\Element->normalizeFieldValue('location')
#5 /Users/Tobias/Development/fiftyfifty-app-cms/vendor/yiisoft/yii2/base/ArrayableTrait.php(126): craft\base\Element->__get('location')
#6 /Users/Tobias/Development/fiftyfifty-app-cms/vendor/craftcms/cms/src/web/View.php(630): yii\base\Model->toArray(Array, Array, false)
#7 /Users/Tobias/Development/fiftyfifty-app-cms/vendor/craftcms/cms/src/helpers/ElementHelper.php(181): craft\web\View->renderObjectTemplate('seller/{{ (_var...', Object(craft\elements\Entry), Array)
#8 /Users/Tobias/Development/fiftyfifty-app-cms/vendor/craftcms/cms/src/helpers/ElementHelper.php(99): craft\helpers\ElementHelper::_renderUriFormat('seller/{slug}', Object(craft\elements\Entry))
#9 /Users/Tobias/Development/fiftyfifty-app-cms/vendor/craftcms/cms/src/validators/ElementUriValidator.php(57): craft\helpers\ElementHelper::setUniqueUri(Object(craft\elements\Entry))
#10 /Users/Tobias/Development/fiftyfifty-app-cms/vendor/yiisoft/yii2/validators/Validator.php(257): craft\validators\ElementUriValidator->validateAttribute(Object(craft\elements\Entry), 'uri')
#11 /Users/Tobias/Development/fiftyfifty-app-cms/vendor/yiisoft/yii2/base/Model.php(367): yii\validators\Validator->validateAttributes(Object(craft\elements\Entry), Array)
#12 /Users/Tobias/Development/fiftyfifty-app-cms/vendor/craftcms/cms/src/services/Elements.php(1981): yii\base\Model->validate()
#13 /Users/Tobias/Development/fiftyfifty-app-cms/vendor/craftcms/cms/src/services/Elements.php(530): craft\services\Elements->_saveElementInternal(Object(craft\elements\Entry), true, false, NULL)
#14 /Users/Tobias/Development/fiftyfifty-app-cms/vendor/craftcms/cms/src/services/Drafts.php(206): craft\services\Elements->saveElement(Object(craft\elements\Entry))
#15 /Users/Tobias/Development/fiftyfifty-app-cms/vendor/craftcms/cms/src/controllers/EntryRevisionsController.php(124): craft\services\Drafts->saveElementAsDraft(Object(craft\elements\Entry), 1)
#16 [internal function]: craft\controllers\EntryRevisionsController->actionCreateDraft(Object(craft\models\Section), Object(craft\models\Site))
#17 /Users/Tobias/Development/fiftyfifty-app-cms/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#18 /Users/Tobias/Development/fiftyfifty-app-cms/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#19 /Users/Tobias/Development/fiftyfifty-app-cms/vendor/craftcms/cms/src/web/Controller.php(178): yii\base\Controller->runAction('create-draft', Array)
#20 /Users/Tobias/Development/fiftyfifty-app-cms/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('create-draft', Array)
#21 /Users/Tobias/Development/fiftyfifty-app-cms/vendor/craftcms/cms/src/web/Application.php(290): yii\base\Module->runAction('entry-revisions...', Array)
#22 /Users/Tobias/Development/fiftyfifty-app-cms/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('entry-revisions...', Array)
#23 /Users/Tobias/Development/fiftyfifty-app-cms/vendor/craftcms/cms/src/web/Application.php(275): yii\web\Application->handleRequest(Object(craft\web\Request))
#24 /Users/Tobias/Development/fiftyfifty-app-cms/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#25 /Users/Tobias/Development/fiftyfifty-app-cms/web/index.php(21): yii\base\Application->run()
#26 {main}`

**Comment by niektenhoopen** [comment]
Are you on PHP 7.0 or earlier by any chance?

**Comment by olivierbon** [comment]
@niektenhoopen @tsawitzki Yes, PHP version is the issue here. Visibility modifiers for constants aren't available before 7.1

**Comment by tsawitzki** [comment]
Thanks, this was the error indeed! SOLVED!
