### ISSUE TITLE
syntax error, unexpected '<<' (T_SL)

### ISSUE THREAD

**Issue by nikesh-method** [nthmedia/entry-gps-coordinates#9]
I have format my mac and installed mamp from beginning, 
I cloned my craft cms website from git repo. 
connected database and redirected mamp to craft folder.
I am getting " syntax error, unexpected '<<' (T_SL) " while running localhost from mamp. here are the screenshots of error and php version.
![Screen Shot 2020-04-28 at 4 39 09 PM](https://user-images.githubusercontent.com/60586020/80449029-2946bc00-8972-11ea-8ad7-48f77bc6b9cc.png)
![Screen Shot 2020-04-28 at 4 39 52 PM](https://user-images.githubusercontent.com/60586020/80449033-2ba91600-8972-11ea-987c-c13eada3b0bc.png)

**Comment by niektenhoopen** [comment]
Looks like a regular unresolved git merge conflict on your side. I can't imagine that I committed an unresolved merge conflict to be honest. 

Did you make any changes to this plugin and included the vendor file to your git repository?

If not: which version of the plugin are you using?

**Comment by nikesh-method** [comment]
yup , that was merge conflict. 
thanks issue solved :)
